//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.DancingGoatCore;

[assembly: RegisterDocumentType(SiteDescription.CLASS_NAME, typeof(SiteDescription))]

namespace CMS.DocumentEngine.Types.DancingGoatCore
{
	/// <summary>
	/// Represents a content item of type SiteDescription.
	/// </summary>
	public partial class SiteDescription : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DancingGoatCore.SiteDescription";


		/// <summary>
		/// The instance of the class that provides extended API for working with SiteDescription fields.
		/// </summary>
		private readonly SiteDescriptionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ContactID.
		/// </summary>
		[DatabaseIDField]
		public int SiteDescriptionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SiteDescriptionID"), 0);
			}
			set
			{
				SetValue("SiteDescriptionID", value);
			}
		}


		/// <summary>
		/// Long Content.
		/// </summary>
		[DatabaseField]
		public string LongContent
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LongContent"), @"");
			}
			set
			{
				SetValue("LongContent", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with SiteDescription fields.
		/// </summary>
		[RegisterProperty]
		public SiteDescriptionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with SiteDescription fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class SiteDescriptionFields : AbstractHierarchicalObject<SiteDescriptionFields>
		{
			/// <summary>
			/// The content item of type SiteDescription that is a target of the extended API.
			/// </summary>
			private readonly SiteDescription mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="SiteDescriptionFields" /> class with the specified content item of type SiteDescription.
			/// </summary>
			/// <param name="instance">The content item of type SiteDescription that is a target of the extended API.</param>
			public SiteDescriptionFields(SiteDescription instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ContactID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.SiteDescriptionID;
				}
				set
				{
					mInstance.SiteDescriptionID = value;
				}
			}


			/// <summary>
			/// Long Content.
			/// </summary>
			public string LongSiteContent
			{
				get
				{
					return mInstance.LongContent;
				}
				set
				{
					mInstance.LongContent = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="SiteDescription" /> class.
		/// </summary>
		public SiteDescription() : base(CLASS_NAME)
		{
			mFields = new SiteDescriptionFields(this);
		}

		#endregion
	}
}