//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.KomatsuDemo;

[assembly: RegisterDocumentType(VideoBanner.CLASS_NAME, typeof(VideoBanner))]

namespace CMS.DocumentEngine.Types.KomatsuDemo
{
	/// <summary>
	/// Represents a content item of type VideoBanner.
	/// </summary>
	public partial class VideoBanner : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "KomatsuDemo.VideoBanner";


		/// <summary>
		/// The instance of the class that provides extended API for working with VideoBanner fields.
		/// </summary>
		private readonly VideoBannerFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// VideoBannerID.
		/// </summary>
		[DatabaseIDField]
		public int VideoBannerID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("VideoBannerID"), 0);
			}
			set
			{
				SetValue("VideoBannerID", value);
			}
		}


		/// <summary>
		/// Video Path.
		/// </summary>
		[DatabaseField]
		public string VideoPath
		{
			get
			{
				return ValidationHelper.GetString(GetValue("VideoPath"), @"");
			}
			set
			{
				SetValue("VideoPath", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with VideoBanner fields.
		/// </summary>
		[RegisterProperty]
		public VideoBannerFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with VideoBanner fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class VideoBannerFields : AbstractHierarchicalObject<VideoBannerFields>
		{
			/// <summary>
			/// The content item of type VideoBanner that is a target of the extended API.
			/// </summary>
			private readonly VideoBanner mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="VideoBannerFields" /> class with the specified content item of type VideoBanner.
			/// </summary>
			/// <param name="instance">The content item of type VideoBanner that is a target of the extended API.</param>
			public VideoBannerFields(VideoBanner instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// VideoBannerID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.VideoBannerID;
				}
				set
				{
					mInstance.VideoBannerID = value;
				}
			}


			/// <summary>
			/// Video Path.
			/// </summary>
			public string _VideoPath
			{
				get
				{
					return mInstance.VideoPath;
				}
				set
				{
					mInstance.VideoPath = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="VideoBanner" /> class.
		/// </summary>
		public VideoBanner() : base(CLASS_NAME)
		{
			mFields = new VideoBannerFields(this);
		}

		#endregion
	}
}