//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.KomatsuDemo;

[assembly: RegisterDocumentType(DescriptionSite.CLASS_NAME, typeof(DescriptionSite))]

namespace CMS.DocumentEngine.Types.KomatsuDemo
{
	/// <summary>
	/// Represents a content item of type DescriptionSite.
	/// </summary>
	public partial class DescriptionSite : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "KomatsuDemo.DescriptionSite";


		/// <summary>
		/// The instance of the class that provides extended API for working with DescriptionSite fields.
		/// </summary>
		private readonly DescriptionSiteFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// DescriptionSiteID.
		/// </summary>
		[DatabaseIDField]
		public int DescriptionSiteID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("DescriptionSiteID"), 0);
			}
			set
			{
				SetValue("DescriptionSiteID", value);
			}
		}


		/// <summary>
		/// Content Site Description.
		/// </summary>
		[DatabaseField]
		public string ContentDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContentDescription"), @"");
			}
			set
			{
				SetValue("ContentDescription", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with DescriptionSite fields.
		/// </summary>
		[RegisterProperty]
		public DescriptionSiteFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with DescriptionSite fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class DescriptionSiteFields : AbstractHierarchicalObject<DescriptionSiteFields>
		{
			/// <summary>
			/// The content item of type DescriptionSite that is a target of the extended API.
			/// </summary>
			private readonly DescriptionSite mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="DescriptionSiteFields" /> class with the specified content item of type DescriptionSite.
			/// </summary>
			/// <param name="instance">The content item of type DescriptionSite that is a target of the extended API.</param>
			public DescriptionSiteFields(DescriptionSite instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// DescriptionSiteID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.DescriptionSiteID;
				}
				set
				{
					mInstance.DescriptionSiteID = value;
				}
			}


			/// <summary>
			/// Content Site Description.
			/// </summary>
			public string ContentDescription
			{
				get
				{
					return mInstance.ContentDescription;
				}
				set
				{
					mInstance.ContentDescription = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="DescriptionSite" /> class.
		/// </summary>
		public DescriptionSite() : base(CLASS_NAME)
		{
			mFields = new DescriptionSiteFields(this);
		}

		#endregion
	}
}