//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.DancingGoatCore;

[assembly: RegisterDocumentType(Cafe.CLASS_NAME, typeof(Cafe))]

namespace CMS.DocumentEngine.Types.DancingGoatCore
{
	/// <summary>
	/// Represents a content item of type Cafe.
	/// </summary>
	public partial class Cafe : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DancingGoatCore.Cafe";


		/// <summary>
		/// The instance of the class that provides extended API for working with Cafe fields.
		/// </summary>
		private readonly CafeFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// CafeID.
		/// </summary>
		[DatabaseIDField]
		public int CafeID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("CafeID"), 0);
			}
			set
			{
				SetValue("CafeID", value);
			}
		}


		/// <summary>
		/// Horsepower.
		/// </summary>
		[DatabaseField]
		public string Horsepower
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Horsepower"), @"");
			}
			set
			{
				SetValue("Horsepower", value);
			}
		}


		/// <summary>
		/// Photo.
		/// </summary>
		[DatabaseField]
		public Guid ProductPhoto
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("ProductPhoto"), Guid.Empty);
			}
			set
			{
				SetValue("ProductPhoto", value);
			}
		}


		/// <summary>
		/// Operating weight.
		/// </summary>
		[DatabaseField]
		public string OperatingWeight
		{
			get
			{
				return ValidationHelper.GetString(GetValue("OperatingWeight"), @"");
			}
			set
			{
				SetValue("OperatingWeight", value);
			}
		}


		/// <summary>
		/// Blade Capacity.
		/// </summary>
		[DatabaseField]
		public string BladeCapacity
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BladeCapacity"), @"");
			}
			set
			{
				SetValue("BladeCapacity", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Cafe fields.
		/// </summary>
		[RegisterProperty]
		public CafeFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Cafe fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CafeFields : AbstractHierarchicalObject<CafeFields>
		{
			/// <summary>
			/// The content item of type Cafe that is a target of the extended API.
			/// </summary>
			private readonly Cafe mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CafeFields" /> class with the specified content item of type Cafe.
			/// </summary>
			/// <param name="instance">The content item of type Cafe that is a target of the extended API.</param>
			public CafeFields(Cafe instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// CafeID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.CafeID;
				}
				set
				{
					mInstance.CafeID = value;
				}
			}


			/// <summary>
			/// Horsepower.
			/// </summary>
			public string Horsepower
			{
				get
				{
					return mInstance.Horsepower;
				}
				set
				{
					mInstance.Horsepower = value;
				}
			}


			/// <summary>
			/// Photo.
			/// </summary>
			public DocumentAttachment ProductPhoto
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("ProductPhoto");
				}
			}


			/// <summary>
			/// Operating weight.
			/// </summary>
			public string OperatingWeight
			{
				get
				{
					return mInstance.OperatingWeight;
				}
				set
				{
					mInstance.OperatingWeight = value;
				}
			}


			/// <summary>
			/// Blade Capacity.
			/// </summary>
			public string BladeCapacity
			{
				get
				{
					return mInstance.BladeCapacity;
				}
				set
				{
					mInstance.BladeCapacity = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Cafe" /> class.
		/// </summary>
		public Cafe() : base(CLASS_NAME)
		{
			mFields = new CafeFields(this);
		}

		#endregion
	}
}